# VIDEO 1 DATAFRAME BASICS

In [4]:
import pandas as pd
#creating the dataframe
premier_league = pd.read_csv("results.csv")
stats_premier = pd.read_csv("stats.csv")
premier_league

,home_team,away_team,home_goals,away_goals,result,season
0,Sheffield United,Liverpool,1.0,1.0,D,2006-2007
1,Arsenal,Aston Villa,1.0,1.0,D,2006-2007
2,Everton,Watford,2.0,1.0,H,2006-2007
3,Newcastle United,Wigan Athletic,2.0,1.0,H,2006-2007
4,Portsmouth,Blackburn Rovers,3.0,0.0,H,2006-2007
...,...,...,...,...,...,...
4555,Newcastle United,Chelsea,3.0,0.0,H,2017-2018
4556,Southampton,Manchester City,0.0,1.0,A,2017-2018
4557,Swansea City,Stoke City,1.0,2.0,A,2017-2018
4558,Tottenham Hotspur,Leicester City,5.0,4.0,H,2017-2018
4559,West Ham United,Everton,3.0,1.0,H,2017-2018

In [2]:
premier_league.shape

(4560, 6)

In [9]:
stats_premier.shape

(240, 42)

In [10]:
#showing all columns
stats_premier.columns

Index(['team', 'wins', 'losses', 'goals', 'total_yel_card', 'total_red_card',
       'total_scoring_att', 'ontarget_scoring_att', 'hit_woodwork',
       'att_hd_goal', 'att_pen_goal', 'att_freekick_goal', 'att_ibox_goal',
       'att_obox_goal', 'goal_fastbreak', 'total_offside', 'clean_sheet',
       'goals_conceded', 'saves', 'outfielder_block', 'interception',
       'total_tackle', 'last_man_tackle', 'total_clearance', 'head_clearance',
       'own_goals', 'penalty_conceded', 'pen_goals_conceded', 'total_pass',
       'total_through_ball', 'total_long_balls', 'backward_pass',
       'total_cross', 'corner_taken', 'touches', 'big_chance_missed',
       'clearance_off_line', 'dispossessed', 'penalty_save',
       'total_high_claim', 'punches', 'season'],
      dtype='object')

In [12]:
stats_premier.team #stats_premier['team']

0         Manchester United
1                   Chelsea
2                 Liverpool
3                   Arsenal
4         Tottenham Hotspur
               ...
235       Huddersfield Town
236            Swansea City
237             Southampton
238              Stoke City
239    West Bromwich Albion
Name: team, Length: 240, dtype: object

In [13]:
type(stats_premier['team'])

pandas.core.series.Series

In [17]:
stats_premier[['team', 'wins', 'losses', 'season']] #showing more than 2 or more columns

                     team  wins  losses     season
0       Manchester United  28.0     5.0  2006-2007
1                 Chelsea  24.0     3.0  2006-2007
2               Liverpool  20.0    10.0  2006-2007
3                 Arsenal  19.0     8.0  2006-2007
4       Tottenham Hotspur  17.0    12.0  2006-2007
..                    ...   ...     ...        ...
235     Huddersfield Town   9.0    19.0  2017-2018
236          Swansea City   8.0    21.0  2017-2018
237           Southampton   7.0    16.0  2017-2018
238            Stoke City   7.0    19.0  2017-2018
239  West Bromwich Albion   6.0    19.0  2017-2018

[240 rows x 4 columns]

In [22]:
stats_premier['goals'].std() #max value, mean(average), min(minimun value), std(standard deviation)

16.203473786861455

In [23]:
stats_premier.describe() #some stats about columns

,wins,losses,goals,total_yel_card,total_red_card,total_scoring_att,ontarget_scoring_att,hit_woodwork,att_hd_goal,att_pen_goal,...,backward_pass,total_cross,corner_taken,touches,big_chance_missed,clearance_off_line,dispossessed,penalty_save,total_high_claim,punches
count,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000,...,160.000000,240.000000,240.000000,240.000000,160.000000,240.000000,220.000000,240.000000,240.000000,240.000000
mean,14.150000,14.150000,51.062500,61.079167,2.862500,514.241667,168.116667,12.283333,9.016667,3.650000,...,2465.650000,831.370833,207.191667,23908.962500,39.200000,4.991667,472.968182,0.837500,54.920833,22.783333
std,6.022482,5.596846,16.203474,10.078249,1.802442,95.979164,38.748882,4.820950,3.659077,2.052246,...,491.135729,118.551756,35.933177,3247.161627,13.391915,2.804646,84.653006,0.947718,18.780999,9.148869
min,1.000000,2.000000,20.000000,38.000000,0.000000,338.000000,94.000000,4.000000,1.000000,0.000000,...,1382.000000,572.000000,136.000000,16772.000000,18.000000,0.000000,296.000000,0.000000,19.000000,4.000000
25%,10.000000,10.000000,40.000000,54.000000,1.000000,441.000000,140.000000,9.000000,6.000000,2.000000,...,2120.000000,749.000000,180.000000,21577.000000,30.000000,3.000000,412.750000,0.000000,40.000000,17.000000
50%,12.000000,15.000000,47.000000,60.500000,3.000000,498.500000,158.500000,11.500000,9.000000,3.500000,...,2374.000000,818.000000,201.000000,23168.500000,37.000000,5.000000,465.000000,1.000000,53.000000,22.000000
75%,18.000000,19.000000,61.000000,67.000000,4.000000,572.000000,194.250000,15.000000,12.000000,5.000000,...,2808.750000,911.250000,230.000000,26294.000000,44.250000,7.000000,522.500000,1.000000,68.000000,27.000000
max,32.000000,29.000000,106.000000,94.000000,9.000000,834.000000,288.000000,33.000000,18.000000,11.000000,...,4546.000000,1156.000000,309.000000,35130.000000,88.000000,16.000000,776.000000,5.000000,118.000000,66.000000

## Filters and conditions

In [24]:
stats_premier[stats_premier.goals > 75] #teams with more than 75 goals

,team,wins,losses,goals,total_yel_card,total_red_card,total_scoring_att,ontarget_scoring_att,hit_woodwork,att_hd_goal,...,total_cross,corner_taken,touches,big_chance_missed,clearance_off_line,dispossessed,penalty_save,total_high_claim,punches,season
0,Manchester United,28.0,5.0,83.0,60.0,1.0,698.0,256.0,21.0,12.0,...,918.0,258.0,25686.0,NaN,1.0,NaN,2.0,37.0,25.0,2006-2007
20,Manchester United,27.0,5.0,80.0,51.0,2.0,696.0,260.0,16.0,12.0,...,936.0,261.0,26620.0,NaN,10.0,627.0,0.0,47.0,23.0,2007-2008
42,Liverpool,25.0,2.0,77.0,50.0,0.0,736.0,224.0,26.0,14.0,...,1021.0,269.0,29875.0,NaN,0.0,470.0,0.0,61.0,19.0,2008-2009
60,Chelsea,27.0,6.0,103.0,54.0,5.0,834.0,288.0,13.0,16.0,...,1083.0,286.0,28914.0,NaN,3.0,503.0,1.0,87.0,30.0,2009-2010
61,Manchester United,27.0,7.0,86.0,49.0,4.0,695.0,221.0,12.0,14.0,...,1156.0,297.0,28968.0,NaN,2.0,622.0,0.0,65.0,18.0,2009-2010
62,Arsenal,23.0,9.0,83.0,56.0,1.0,660.0,233.0,15.0,11.0,...,1023.0,257.0,29807.0,NaN,3.0,713.0,2.0,75.0,24.0,2009-2010
80,Manchester United,23.0,4.0,78.0,56.0,3.0,618.0,212.0,15.0,18.0,...,1005.0,243.0,26671.0,50.0,2.0,471.0,0.0,45.0,16.0,2010-2011
100,Manchester City,28.0,5.0,93.0,51.0,5.0,738.0,250.0,21.0,10.0,...,843.0,269.0,28620.0,65.0,6.0,480.0,1.0,39.0,21.0,2011-2012
101,Manchester United,28.0,5.0,89.0,51.0,1.0,646.0,243.0,17.0,16.0,...,1018.0,279.0,28113.0,64.0,3.0,521.0,1.0,37.0,26.0,2011-2012
120,Manchester United,28.0,5.0,86.0,57.0,1.0,561.0,213.0,24.0,14.0,...,962.0,218.0,27264.0,65.0,5.0,506.0,0.0,38.0,28.0,2012-2013
140,Manchester City,27.0,6.0,102.0,72.0,1.0,673.0,238.0,19.0,10.0,...,892.0,283.0,28341.0,59.0,0.0,411.0,0.0,64.0,31.0,2013-2014
141,Liverpool,26.0,6.0,101.0,54.0,1.0,651.0,258.0,27.0,14.0,...,643.0,224.0,28172.0,64.0,5.0,427.0,1.0,36.0,29.0,2013-2014
161,Manchester City,24.0,7.0,83.0,77.0,2.0,670.0,229.0,18.0,5.0,...,795.0,277.0,29652.0,42.0,1.0,546.0,1.0,52.0,31.0,2014-2015
200,Chelsea,30.0,5.0,85.0,72.0,0.0,580.0,204.0,17.0,8.0,...,688.0,218.0,27658.0,32.0,3.0,436.0,0.0,38.0,18.0,2016-2017
201,Tottenham Hotspur,26.0,4.0,86.0,62.0,0.0,669.0,257.0,22.0,10.0,...,761.0,273.0,28150.0,41.0,1.0,484.0,0.0,21.0,11.0,2016-2017
202,Arsenal,23.0,9.0,77.0,68.0,3.0,566.0,201.0,17.0,17.0,...,697.0,227.0,28931.0,41.0,1.0,465.0,0.0,36.0,10.0,2016-2017
203,Manchester City,23.0,6.0,80.0,71.0,4.0,633.0,216.0,20.0,8.0,...,801.0,280.0,30363.0,48.0,4.0,465.0,2.0,26.0,20.0,2016-2017
204,Liverpool,22.0,6.0,78.0,54.0,0.0,640.0,236.0,18.0,12.0,...,812.0,249.0,30071.0,35.0,0.0,472.0,2.0,36.0,26.0,2016-2017
220,Manchester City,32.0,2.0,106.0,59.0,2.0,665.0,265.0,23.0,12.0,...,691.0,284.0,35130.0,63.0,4.0,406.0,2.0,21.0,15.0,2017-2018
224,Liverpool,21.0,5.0,84.0,44.0,1.0,638.0,233.0,16.0,12.0,...,764.0,230.0,30324.0,61.0,2.0,447.0,2.0,25.0,20.0,2017-2018

In [25]:
stats_premier[stats_premier.total_yel_card > 55]

,team,wins,losses,goals,total_yel_card,total_red_card,total_scoring_att,ontarget_scoring_att,hit_woodwork,att_hd_goal,...,total_cross,corner_taken,touches,big_chance_missed,clearance_off_line,dispossessed,penalty_save,total_high_claim,punches,season
0,Manchester United,28.0,5.0,83.0,60.0,1.0,698.0,256.0,21.0,12.0,...,918.0,258.0,25686.0,NaN,1.0,NaN,2.0,37.0,25.0,2006-2007
1,Chelsea,24.0,3.0,64.0,62.0,4.0,636.0,216.0,14.0,16.0,...,897.0,231.0,24010.0,NaN,2.0,NaN,1.0,74.0,22.0,2006-2007
3,Arsenal,19.0,8.0,63.0,59.0,3.0,638.0,226.0,19.0,10.0,...,873.0,278.0,25592.0,NaN,1.0,NaN,0.0,88.0,27.0,2006-2007
5,Bolton Wanderers,16.0,14.0,47.0,84.0,4.0,404.0,120.0,7.0,10.0,...,942.0,217.0,18932.0,NaN,6.0,NaN,2.0,44.0,21.0,2006-2007
7,Blackburn Rovers,15.0,16.0,52.0,77.0,6.0,478.0,155.0,5.0,12.0,...,911.0,205.0,20812.0,NaN,8.0,NaN,5.0,56.0,25.0,2006-2007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,West Ham United,10.0,16.0,48.0,73.0,2.0,372.0,133.0,14.0,6.0,...,732.0,161.0,21928.0,29.0,4.0,390.0,1.0,19.0,19.0,2017-2018
235,Huddersfield Town,9.0,19.0,28.0,62.0,3.0,362.0,109.0,8.0,5.0,...,765.0,165.0,22619.0,21.0,6.0,416.0,2.0,31.0,24.0,2017-2018
237,Southampton,7.0,16.0,37.0,63.0,2.0,450.0,145.0,15.0,7.0,...,800.0,227.0,24639.0,37.0,4.0,379.0,1.0,29.0,13.0,2017-2018
238,Stoke City,7.0,19.0,35.0,62.0,1.0,384.0,132.0,8.0,8.0,...,598.0,136.0,20368.0,33.0,3.0,402.0,0.0,27.0,14.0,2017-2018
239,West Bromwich Albion,6.0,19.0,31.0,73.0,1.0,378.0,114.0,7.0,10.0,...,784.0,176.0,20552.0,28.0,3.0,446.0,0.0,40.0,5.0,2017-2018

In [32]:
stats_premier[stats_premier.goals == stats_premier.goals.max()]

,team,wins,losses,goals,total_yel_card,total_red_card,total_scoring_att,ontarget_scoring_att,hit_woodwork,att_hd_goal,...,total_cross,corner_taken,touches,big_chance_missed,clearance_off_line,dispossessed,penalty_save,total_high_claim,punches,season
220,Manchester City,32.0,2.0,106.0,59.0,2.0,665.0,265.0,23.0,12.0,...,691.0,284.0,35130.0,63.0,4.0,406.0,2.0,21.0,15.0,2017-2018

In [39]:
#showing some estra data for teams with more than 80 goals 
stats_premier[['season', 'team', 'goals', 'wins', 'losses']][stats_premier.goals > 80]

        season               team  goals  wins  losses
0    2006-2007  Manchester United   83.0  28.0     5.0
60   2009-2010            Chelsea  103.0  27.0     6.0
61   2009-2010  Manchester United   86.0  27.0     7.0
62   2009-2010            Arsenal   83.0  23.0     9.0
100  2011-2012    Manchester City   93.0  28.0     5.0
101  2011-2012  Manchester United   89.0  28.0     5.0
120  2012-2013  Manchester United   86.0  28.0     5.0
140  2013-2014    Manchester City  102.0  27.0     6.0
141  2013-2014          Liverpool  101.0  26.0     6.0
161  2014-2015    Manchester City   83.0  24.0     7.0
200  2016-2017            Chelsea   85.0  30.0     5.0
201  2016-2017  Tottenham Hotspur   86.0  26.0     4.0
220  2017-2018    Manchester City  106.0  32.0     2.0
224  2017-2018          Liverpool   84.0  21.0     5.0

In [53]:
stats_premier.set_index('team', inplace=True) #fixing team as the index

In [54]:
stats_premier.loc['Manchester United'] #show Manchester United results

,wins,losses,goals,total_yel_card,total_red_card,total_scoring_att,ontarget_scoring_att,hit_woodwork,att_hd_goal,att_pen_goal,...,backward_pass,total_cross,corner_taken,touches,big_chance_missed,clearance_off_line,dispossessed,penalty_save,total_high_claim,punches
team,,,,,,,,,,,,,,,,,,,,,
Manchester United,28.0,5.0,83.0,60.0,1.0,698.0,256.0,21.0,12.0,5.0,...,NaN,918.0,258.0,25686.0,NaN,1.0,NaN,2.0,37.0,25.0
Manchester United,27.0,5.0,80.0,51.0,2.0,696.0,260.0,16.0,12.0,6.0,...,NaN,936.0,261.0,26620.0,NaN,10.0,627.0,0.0,47.0,23.0
Manchester United,28.0,4.0,68.0,61.0,5.0,715.0,230.0,9.0,7.0,4.0,...,NaN,1039.0,257.0,30077.0,NaN,3.0,579.0,0.0,56.0,22.0
Manchester United,27.0,7.0,86.0,49.0,4.0,695.0,221.0,12.0,14.0,6.0,...,NaN,1156.0,297.0,28968.0,NaN,2.0,622.0,0.0,65.0,18.0
Manchester United,23.0,4.0,78.0,56.0,3.0,618.0,212.0,15.0,18.0,3.0,...,2411.0,1005.0,243.0,26671.0,50.0,2.0,471.0,0.0,45.0,16.0
Manchester United,28.0,5.0,89.0,51.0,1.0,646.0,243.0,17.0,16.0,9.0,...,2765.0,1018.0,279.0,28113.0,64.0,3.0,521.0,1.0,37.0,26.0
Manchester United,28.0,5.0,86.0,57.0,1.0,561.0,213.0,24.0,14.0,4.0,...,2727.0,962.0,218.0,27264.0,65.0,5.0,506.0,0.0,38.0,28.0
Manchester United,19.0,12.0,64.0,66.0,3.0,526.0,183.0,16.0,10.0,5.0,...,2898.0,1000.0,216.0,27367.0,38.0,1.0,491.0,0.0,32.0,14.0
Manchester United,20.0,8.0,62.0,64.0,5.0,512.0,180.0,11.0,12.0,3.0,...,3457.0,908.0,214.0,29044.0,43.0,5.0,393.0,1.0,33.0,7.0
Manchester United,19.0,10.0,49.0,65.0,1.0,430.0,144.0,9.0,5.0,3.0,...,3221.0,786.0,228.0,27542.0,28.0,4.0,522.0,0.0,29.0,13.0
Manchester United,18.0,5.0,54.0,78.0,2.0,591.0,210.0,19.0,9.0,3.0,...,3177.0,848.0,217.0,28119.0,50.0,1.0,389.0,1.0,32.0,4.0
Manchester United,25.0,7.0,68.0,64.0,1.0,512.0,178.0,16.0,12.0,1.0,...,2878.0,753.0,220.0,27525.0,42.0,4.0,399.0,0.0,20.0,6.0

In [50]:
#stats_premier.reset_index(inplace=True) #reset the index

In [55]:
stats_premier.loc[["Manchester United", "Liverpool"]] # should be fixed 'teams' like index

,wins,losses,goals,total_yel_card,total_red_card,total_scoring_att,ontarget_scoring_att,hit_woodwork,att_hd_goal,att_pen_goal,...,backward_pass,total_cross,corner_taken,touches,big_chance_missed,clearance_off_line,dispossessed,penalty_save,total_high_claim,punches
team,,,,,,,,,,,,,,,,,,,,,
Manchester United,28.0,5.0,83.0,60.0,1.0,698.0,256.0,21.0,12.0,5.0,...,NaN,918.0,258.0,25686.0,NaN,1.0,NaN,2.0,37.0,25.0
Manchester United,27.0,5.0,80.0,51.0,2.0,696.0,260.0,16.0,12.0,6.0,...,NaN,936.0,261.0,26620.0,NaN,10.0,627.0,0.0,47.0,23.0
Manchester United,28.0,4.0,68.0,61.0,5.0,715.0,230.0,9.0,7.0,4.0,...,NaN,1039.0,257.0,30077.0,NaN,3.0,579.0,0.0,56.0,22.0
Manchester United,27.0,7.0,86.0,49.0,4.0,695.0,221.0,12.0,14.0,6.0,...,NaN,1156.0,297.0,28968.0,NaN,2.0,622.0,0.0,65.0,18.0
Manchester United,23.0,4.0,78.0,56.0,3.0,618.0,212.0,15.0,18.0,3.0,...,2411.0,1005.0,243.0,26671.0,50.0,2.0,471.0,0.0,45.0,16.0
Manchester United,28.0,5.0,89.0,51.0,1.0,646.0,243.0,17.0,16.0,9.0,...,2765.0,1018.0,279.0,28113.0,64.0,3.0,521.0,1.0,37.0,26.0
Manchester United,28.0,5.0,86.0,57.0,1.0,561.0,213.0,24.0,14.0,4.0,...,2727.0,962.0,218.0,27264.0,65.0,5.0,506.0,0.0,38.0,28.0
Manchester United,19.0,12.0,64.0,66.0,3.0,526.0,183.0,16.0,10.0,5.0,...,2898.0,1000.0,216.0,27367.0,38.0,1.0,491.0,0.0,32.0,14.0
Manchester United,20.0,8.0,62.0,64.0,5.0,512.0,180.0,11.0,12.0,3.0,...,3457.0,908.0,214.0,29044.0,43.0,5.0,393.0,1.0,33.0,7.0
Manchester United,19.0,10.0,49.0,65.0,1.0,430.0,144.0,9.0,5.0,3.0,...,3221.0,786.0,228.0,27542.0,28.0,4.0,522.0,0.0,29.0,13.0
Manchester United,18.0,5.0,54.0,78.0,2.0,591.0,210.0,19.0,9.0,3.0,...,3177.0,848.0,217.0,28119.0,50.0,1.0,389.0,1.0,32.0,4.0
Manchester United,25.0,7.0,68.0,64.0,1.0,512.0,178.0,16.0,12.0,1.0,...,2878.0,753.0,220.0,27525.0,42.0,4.0,399.0,0.0,20.0,6.0
Liverpool,20.0,10.0,57.0,44.0,0.0,668.0,214.0,15.0,8.0,6.0,...,NaN,1107.0,282.0,24150.0,NaN,1.0,NaN,0.0,51.0,27.0
Liverpool,21.0,4.0,67.0,45.0,1.0,686.0,214.0,13.0,7.0,5.0,...,NaN,932.0,237.0,25857.0,NaN,4.0,613.0,1.0,42.0,22.0
Liverpool,25.0,2.0,77.0,50.0,0.0,736.0,224.0,26.0,14.0,5.0,...,NaN,1021.0,269.0,29875.0,NaN,0.0,470.0,0.0,61.0,19.0
Liverpool,18.0,11.0,61.0,55.0,5.0,642.0,189.0,20.0,6.0,3.0,...,NaN,1017.0,268.0,28704.0,NaN,1.0,489.0,1.0,52.0,28.0
Liverpool,17.0,14.0,59.0,63.0,2.0,582.0,205.0,12.0,8.0,6.0,...,2500.0,824.0,212.0,24941.0,43.0,6.0,493.0,0.0,74.0,26.0
Liverpool,14.0,14.0,47.0,53.0,5.0,667.0,207.0,33.0,8.0,1.0,...,2991.0,1103.0,309.0,26450.0,66.0,2.0,440.0,1.0,22.0,19.0
Liverpool,16.0,9.0,71.0,54.0,2.0,739.0,232.0,19.0,9.0,5.0,...,3004.0,794.0,284.0,27722.0,61.0,3.0,529.0,1.0,38.0,23.0
Liverpool,26.0,6.0,101.0,54.0,1.0,651.0,258.0,27.0,14.0,10.0,...,2959.0,643.0,224.0,28172.0,64.0,5.0,427.0,1.0,36.0,29.0
Liverpool,18.0,12.0,52.0,66.0,3.0,590.0,192.0,12.0,5.0,5.0,...,2787.0,638.0,198.0,27353.0,34.0,3.0,468.0,2.0,38.0,41.0
Liverpool,16.0,10.0,63.0,61.0,3.0,629.0,202.0,16.0,12.0,2.0,...,2842.0,780.0,265.0,27890.0,36.0,2.0,560.0,1.0,41.0,18.0
Liverpool,22.0,6.0,78.0,54.0,0.0,640.0,236.0,18.0,12.0,7.0,...,3291.0,812.0,249.0,30071.0,35.0,0.0,472.0,2.0,36.0,26.0
Liverpool,21.0,5.0,84.0,44.0,1.0,638.0,233.0,16.0,12.0,2.0,...,3313.0,764.0,230.0,30324.0,61.0,2.0,447.0,2.0,25.0,20.0